# Generated by Django 5.1 on 2025-08-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelreservatorio',
            name='nivel',
            field=models.IntegerField(),
        ),
    ]
