# Generated by Django 5.2.6 on 2025-09-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivel', '0003_vazaoreservatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vazaoreservatorio',
            name='vazao',
            field=models.IntegerField(),
        ),
    ]
