# Generated by Django 5.2.6 on 2025-09-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivel', '0004_alter_vazaoreservatorio_vazao'),
    ]

    operations = [
        migrations.CreateModel(
            name='BombaReservatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
